spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/shopping_app  
spring.datasource.username=root
spring.datasource.password=root@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
razorpay.key_id=rzp_test_55555
razorpay.key_secret=suji
server.port=8080